# Generated by Django 4.2.7 on 2025-09-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the object was last updated"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title/name",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the object was last updated"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the object was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the object was created"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title/name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Current status of the object",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the object was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the object was created"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title/name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the object was created"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the object was created"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the title/name",
                unique=True,
            ),
        ),
    ]
