# Generated by Django 4.2.7 on 2025-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Current location (city, country)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
    ]
